"""auto_create

Revision ID: a34dca1247cd
Revises: 
Create Date: 2023-07-12 03:10:32.855684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34dca1247cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ketorelationtuples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('object', sa.String(length=255), nullable=True),
    sa.Column('relation', sa.String(length=64), nullable=True),
    sa.Column('subject_id', sa.String(length=255), nullable=True),
    sa.Column('subject_set_namespace', sa.String(length=255), nullable=True),
    sa.Column('subject_set_object', sa.String(length=255), nullable=True),
    sa.Column('subject_set_relation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_ketorelationtuples_id'), 'ketorelationtuples', ['id'], unique=False)
    op.create_table('user_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=12), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_user_id'), 'user_user', ['id'], unique=False)
    op.create_index(op.f('ix_user_user_username'), 'user_user', ['username'], unique=True)
    op.create_table('user_verifycode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('code', sa.String(length=4), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_verifycode_id'), 'user_verifycode', ['id'], unique=False)
    op.create_index(op.f('ix_user_verifycode_mobile'), 'user_verifycode', ['mobile'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_verifycode_mobile'), table_name='user_verifycode')
    op.drop_index(op.f('ix_user_verifycode_id'), table_name='user_verifycode')
    op.drop_table('user_verifycode')
    op.drop_index(op.f('ix_user_user_username'), table_name='user_user')
    op.drop_index(op.f('ix_user_user_id'), table_name='user_user')
    op.drop_table('user_user')
    op.drop_index(op.f('ix_ketorelationtuples_id'), table_name='ketorelationtuples')
    op.drop_table('ketorelationtuples')
    # ### end Alembic commands ###
