"""'user_email'

Revision ID: 9836772e0156
Revises: 0583d3e6e146
Create Date: 2023-07-11 09:34:24.440596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9836772e0156'
down_revision = '0583d3e6e146'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_user', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('user_user', sa.Column('mobile', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_user', 'mobile')
    op.drop_column('user_user', 'email')
    # ### end Alembic commands ###
